linux_test_task:
  container:
    matrix:
      - image: python:3.6
      - image: python:3.7
      - image: python:3.8-rc
      - image: pypy:3.6
  install_script:
    # Needed for some tests
    - apt-get update
    - apt-get install -y man-db
  setup_script:
    - pip install -r requirements/tests.txt
    - pip install .
  test_script:
    - xonsh run-tests.xsh


windows_test_task:
  windows_container:
    matrix:
      # Python 3.6 container was not built for windows
      # - image: python:3.6
      - image: python:3.7
        os_version: 2019
      - image: python:3.8-rc
        os_version: 2019
  setup_script:
    - pip install -r requirements/tests.txt
    - pip install .
  test_script:
    - xonsh run-tests.xsh


mac_test_task:
  osx_instance:
    image: mojave-base
  env:
    PATH: "$HOME/miniconda/bin:$PATH"
    matrix:
      - PYTHON: "3.6"
      - PYTHON: "3.7"
      - PYTHON: "3.8"
  conda_script:
    - wget "https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
  setup_script:
    - pip install -r requirements/tests.txt
    - pip install .
  test_script:
    - xonsh run-tests.xsh


black_task:
  container:
    image: python:3
  setup_script:
    - pip install black==18.9b0
  lint_script:
    - black --check --exclude=xonsh/ply/ xonsh/ xontrib/


docs_task:
  container:
    image: python:3
  setup_script:
    - pip install -r requirements/docs.txt
    - pip install .
  build_script:
    - cd docs && make html
  upload_artifacts:
    path: docs/_build/html/**/*

docs_upload_task:
  # only_if: $CIRRUS_TAG != ''
  depends_on:
    - docs
  env:
    GITHUB_KEY: "ENCRYPTED[106330abbf702222a885536266b89ec82665775a98cc0dbc4ad004990feb11922a0259a7df6a49ed9f94474156da588e]"
  container:
    image: xonsh/xonsh
  ssh_key_file:
    path: $HOME/.ssh/id_ed25519
    variable_name: GITHUB_KEY
  script:
    - xonsh .ci/docs-upload.xsh
