test_task:
  matrix:
    - container:
        matrix:
          - image: python:3.6
          - image: python:3.7
          - image: python:3.8
    - windows_container:
        matrix:
          - image: python:3.6
          - image: python:3.7
          - image: python:3.8
  setup_script:
    - pip install -r requirements/tests.txt
    - pip install .
  test_script:
    - xonsh run-tests.xsh

# mac_test_task:
#   osx_instance:
#     image: mojave-base

black_task:
  container:
    image: python:3-slim
  setup_script:
    - pip install black==18.9b0
  lint_task:
    - black --check --exclude=xonsh/ply/ xonsh/ xontrib/

docs_task:
  container:
    image: python:3-slim
  setup_script:
    - pip install -r requirements/docs.txt
  docs_task:
    - cd docs && make html
  docs_artifacts:
    path: docs/_build/*

# TODO: Docs deploy
