version: 0.9.11.{build}
image:
# - Visual Studio 2015
# - Visual Studio 2017
- Visual Studio 2019
environment:

  matrix:
    # https://www.appveyor.com/docs/windows-images-software/#python
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - XONSH_TEST_ENV: "MSYS2"
      MSYS2_PATH: "C:\\msys64"
    # TODO: Miniconda

matrix:
  allow_failures:
    # ignore MSYS2 test results for now
    - XONSH_TEST_ENV: "MSYS2"

install:
  - ".ci/appveyor/install.cmd"
build: off
test_script:
  - ".ci/appveyor/test.cmd"
